# Akash patil 
aakashgolu1008@gmail.com

## Naive bayes

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [2]:
ir=pd.read_csv('iris.csv')
ir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [3]:
x=ir.iloc[:,:4]
y=ir.iloc[:,-1]

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=5)
x_train

sepal_length  sepal_width  petal_length  petal_width
126           6.2          2.8           4.8          1.8
61            5.9          3.0           4.2          1.5
124           6.7          3.3           5.7          2.1
117           7.7          3.8           6.7          2.2
20            5.4          3.4           1.7          0.2
..            ...          ...           ...          ...
8             4.4          2.9           1.4          0.2
73            6.1          2.8           4.7          1.2
144           6.7          3.3           5.7          2.5
118           7.7          2.6           6.9          2.3
99            5.7          2.8           4.1          1.3

[105 rows x 4 columns]

In [5]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB,BernoulliNB

### GaussianNB

In [6]:
Gnb=GaussianNB()
Gnb.fit(x_train,y_train)
y_pred=Gnb.predict(x_test)
y_pred

array(['versicolor', 'versicolor', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'setosa',
       'setosa', 'virginica', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'setosa', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor'],
      dtype='<U10')

In [7]:
accuracy_score(y_pred,y_test)


0.9333333333333333

In [8]:
confusion_matrix(y_pred,y_test)

array([[15,  0,  0],
       [ 0, 15,  2],
       [ 0,  1, 12]], dtype=int64)

In [9]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.94      0.88      0.91        17
   virginica       0.86      0.92      0.89        13

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.94      0.93      0.93        45



### BernoulliNB

In [10]:
Bnb=BernoulliNB()
Bnb.fit(x_train,y_train)
y_pred=Bnb.predict(x_test)
y_pred

array(['virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [11]:
accuracy_score(y_pred,y_test)

0.3111111111111111

In [12]:
confusion_matrix(y_pred,y_test)

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [15, 16, 14]], dtype=int64)

In [13]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00         0
  versicolor       0.00      0.00      0.00         0
   virginica       1.00      0.31      0.47        45

    accuracy                           0.31        45
   macro avg       0.33      0.10      0.16        45
weighted avg       1.00      0.31      0.47        45



C:\Users\Guru\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Guru\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Guru\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### MultinomialNB

In [14]:
Mnb=MultinomialNB()
Mnb.fit(x_train,y_train)
y_pred=Mnb.predict(x_test)
y_pred

array(['versicolor', 'virginica', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'setosa',
       'setosa', 'virginica', 'virginica', 'setosa', 'setosa',
       'versicolor', 'virginica', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'setosa', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'virginica',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor'],
      dtype='<U10')

In [15]:
accuracy_score(y_pred,y_test)

0.8888888888888888

In [16]:
confusion_matrix(y_pred,y_test)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  5, 14]], dtype=int64)

In [17]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.69      1.00      0.81        11
   virginica       1.00      0.74      0.85        19

    accuracy                           0.89        45
   macro avg       0.90      0.91      0.89        45
weighted avg       0.92      0.89      0.89        45



In [1]:
# GaussianNB - use for indipendent features are contineous numbers
# BernoulliNB - use for indipendent features are 0 & 1 numbers
# MultinomialNB - use for indipendent features are 1,2,3,4.... numbers